### ISSUE TITLE
Display card when image could not be fetched

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#101]
See screenshots. Original tweet has a card:
<img src="https://user-images.githubusercontent.com/1506860/140772233-696c7d87-3c7e-41a7-8b9f-30c6c359d63c.png" width="50%">

On Rockwell there is no card (perhaps we failed to fetch the image), which is OK, but there should at least be an hyperlink.

<img src="https://user-images.githubusercontent.com/1506860/140772223-6d2aed08-775c-432f-935b-caafaeca23e2.png" width="50%">

**Comment by glciampaglia** [comment]
We discussed the issue. What is happening is that the backend will not return a card if any of the image, title, and description could not be fetched. We decided to relax this, and instead we will return the card if the image could not be retrieved (but we could retrieve the title and description). This way there will be no need to append an hyperlink to the tweet text.

**Comment by RobertAndion** [comment]
![image](https://user-images.githubusercontent.com/71728884/141377287-5dcc6e92-fd21-4875-9677-8edbb8818b5e.png)
![image](https://user-images.githubusercontent.com/71728884/141377310-9f5501a6-36a6-452e-8644-9449f8ba60d7.png)

**Comment by RobertAndion** [comment]
This will now show a link added by the user as a "card" or if we are unable to fetch the article it will also appear like this.

**Comment by glciampaglia** [comment]
We will need to improve the current parser to make sure we are able to render correctly as many tweets as possible. Need to re-discuss current approach and see if there is any way to improve. @1449Antonio to study current code.

**Comment by glciampaglia** [comment]
We improved the parser a lot. There probably will be still tweets we cannot load properly, but if we came across any of these consistently, then we may consider reopening the issue. Closing for now.
