### ISSUE TITLE
Store feed clicks, engagements, and telemetry in database

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#104]
We need to:
- [x] Create a new table to store these data with following columns:
  1. user ID (foreign key from user table)
  2. tweet rank
  3. timestamp (starting at t=0, where this is the moment the feed is loaded) 
  4. page number
- [x] Store card clicks in the database
- [x] Store engagements (retweets and likes) in the database
- [x] Store telemetry

## Storing Telemetry 
The frontend tracks telemetry of feed scrolling (see #98), in particular it keeps track of a list of `(tweet rank, timestamp)` pairs, and stores this list locally in the browser. When next button is clicked at the end of each page, we should insert the contents of this list into the database. To store the telemetry data, the endpoint should take the array, plus the page number, and the user ID, and then in the backend we should "unroll" this array so that each entry of the array is a separate row in the table.

**Comment by glciampaglia** [comment]
We discussed and approved a new database layout based on proposal from @saumyabhadani95 @RobertAndion @thomasbiv and @1449Antonio, and we will now implement it.

**Comment by glciampaglia** [comment]
We have implemented storing of card clicks and tweet engagement. We still have a bug when storing the telemetry, we are working on it.

**Comment by saumyabhadani95** [comment]
We are storing the telemetry now. The card clicks wasn't actually done (as mentioned in the above comment). I will close this issue once I am storing the card clicks also.
