### ISSUE TITLE
Give user a chance to recover from error state

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#110]
This is based on #56 and #109. In case (for any reason), the user cannot complete the task, we need to give them a chance to recover from the error. Some possibilities (to discuss with rest of the team):
- Let them go back to authorization and select different Twitter profile;
- Let them go to debriefing and claim credits;
- Let them share feedback and then go to debriefing and claim credit;
- Let them contact us to report error and see if we can fix it.

**Comment by RobertAndion** [comment]
Would we still like the option to go to the authorizer for this or is that no longer part of the workflow?

**Comment by RobertAndion** [comment]
I created a new landing page in the latest PR that can be used now as a redirect back to the authorizer at anytime by using react router to go to the "Landing" component.

**Comment by glciampaglia** [comment]
We have implemented this for the original situation (#56). We now have a way to route users to specific error pages. If we encounter other errors that require the user to be taken to an error page, then we will use those. Closing this now.
