### ISSUE TITLE
Properly handle authentication attempt canceled by user

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#113]
In the Twitter authorization phase, users can click cancel instead of login: 

![image](https://user-images.githubusercontent.com/1506860/144143549-7f2727b0-ade6-4083-8319-83b51106964c.png)

This has the effect of sending back to the app but with a "denied" code instead of the token

http://127.0.0.1:5000/callback?denied=YSZ3vwAAAAABMHNtAAABfXMYzvc

Right now, we do not handle this, so user gets just an error:

![image](https://user-images.githubusercontent.com/1506860/144144031-021dfd6b-a89f-4179-a286-b29ade8d45c5.png)

We should probably take them back to the authentication page and show them a message telling them they canceled the login.

**Comment by RobertAndion** [comment]
This has now been fixed.
