### ISSUE TITLE
Track when rockwell tab is inactive

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#117]
In addition to track scrolling (see #98), we would also like to track when the user is in a different tab. This can happen if they click on a tweet and are taken to a news article outside of rockwell. Knowing when they come back to rockwell's tab would allow us to better measure exposure. 

According to this [SO answer](https://stackoverflow.com/a/63695199), there seems to be a way to do so in javascript:

```javascript
document.addEventListener("visibilitychange", event => {
  if (document.visibilityState == "visible") {
    console.log("tab is active")
  } else {
    console.log("tab is inactive")
  }
})
```

**Comment by glciampaglia** [comment]
Instead of logging into the console, we need to append the millisecond timestamp into the array used for tracking. Since this event is not about a particular tweet, to distinguish it from a scrolling event, we can record -1 to mean that this was a tab switch.

**Comment by RobertAndion** [comment]
This is now complete from the PR @thomasbiv made, -2 timestamp signifies that the tab is in focus and -1 means that it is not.
