### ISSUE TITLE
Long text

### ISSUE THREAD

**Issue by filmenczer** [CSDL-USF/Rockwell#140]
In one tweet, the text was super long. Obviously much longer than the max. tweet length. It seems that the tweet had a link to an article and the full text of the article was included, instead of just a short preview. 

I searched on Twitter and found the tweet: https://twitter.com/jljcolorado/status/1482375110354870276

Here is the linked article: https://www.mcgill.ca/oss/article/covid-19/covid-19-air-both-problem-and-solution

You can see the reason of the problem: the article itself has the `<meta property="og:description" content="...">` and `<meta name="description" content="...">` metadata fields containing the full text of the article. 

This may not be a big problem but the behavior differs from Twitter, which truncates the preview...

**Comment by 1449Antonio** [comment]
So it happened again, this time twitter:description under meta property was too large. 

![LongText](https://user-images.githubusercontent.com/49537223/150701401-95dd7d5b-c195-4050-ae56-b4c010b8cbf6.png)


This leads me to ask whether you would like us to edit the description such that we show a limited amount of characters, and then end the description with a "..." if the description is longer than that limited amount. Looking at the attached tweet, it seems Twitter did that on my end.

https://twitter.com/brosseau_lisa/status/1485323899558629376

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258191

**Comment by filmenczer** [comment]
Yes I would suggest truncation just like Twitter does.
