### ISSUE TITLE
Default profile images not loading properly in quote retweet

### ISSUE THREAD

**Issue by 1449Antonio** [CSDL-USF/Rockwell#151]
I wanted to run some tests, and I discovered this when quote retweeting from my alternate account. I imagine this is a backend issue

![Screenshot from 2022-01-29 16-48-09](https://user-images.githubusercontent.com/49537223/151678622-6f2c96a4-ea70-433a-a06b-332756ee2bc7.png)

and this is the actual quote retweet itself

![default](https://user-images.githubusercontent.com/49537223/151678630-8805a45a-c01a-406c-a4c6-3e21c6f8293e.png)

**Comment by glciampaglia** [comment]
@1449Antonio was this bug fixed in the end?

**Comment by 1449Antonio** [comment]
@glciampaglia We could never replicate the problem again, so there was not much we could do. May have been a temporary problem.

**Comment by glciampaglia** [comment]
OK, closing for now. We can reopen in case we are able to replicate.
