### ISSUE TITLE
Avoid tweets from previous screens in attention check

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#156]
In the attention check, we should display 3 tweets taken at random from the previous feed and 2 distractor tweets selected at random. None of these tweets should have appeared in any previous feed, and should not be used in any later feed. In other words, there should be no overlap between the set of feed tweets and the set of distractor tweets, and no tweet should appear in more than one feed--attention check pair.

**Comment by saumyabhadani95** [comment]
Done.
