### ISSUE TITLE
Resolve redirects

### ISSUE THREAD

**Issue by thomasbiv** [CSDL-USF/Rockwell#173]
An issue has been found where obvious NewsGuard sources are using custom twitter redirect links instead of the links present on the `domains.json` file. This presents a potential issue when trying to mark NewsGuard tweets and rank them. 

Example: Correct Classification 
`[{'url': 'https://t.co/N2Rw7Bvb9k', 'expanded_url': 'https://www.fox13news.com/news/thief-takes-off-with-irreplaceable-items-from-st-pete-womans-storage-unit?taid=6255b39d8999870001e5c4fd&utm_campaign=trueanthem&utm_medium=trueanthem&utm_source=twitter', 'display_url': 'fox13news.com/news/thief-tak…', 'indices': [207, 230]}]`

Example: False Negative with CNN custom redirect `cnn.it` when `domain.json` contains `cnn.com`
`[{'url': 'https://t.co/NKrftCYomE', 'expanded_url': 'https://cnn.it/3rnezkS', 'display_url': 'cnn.it/3rnezkS', 'indices': [228, 251]}]`

**Comment by glciampaglia** [comment]
We discussed it and the solution is to resolve the redirects.
