### ISSUE TITLE
Duplicate key error when loading feed

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#178]
We are experiencing a number of errors, possibly all similar to the one below, when loading the feed. This is happening both on the dev instance, but also on local machines. 

![error_](https://user-images.githubusercontent.com/1506860/166552574-8eb5736e-8b03-4617-a176-89780c4666fd.png)

@1449Antonio please add text instead of image.

We need to discuss this further.

**Comment by saumyabhadani95** [comment]
Resolved and updated on the main branch. The platform on the main branch shows all the feeds now
