### ISSUE TITLE
Collect training data for screened participants

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#18]
After we have screened the survey participants, we need to start collecting training data for the recommendation algorithms. 

We need two sets of engagement data for a given respondent:
- _Positives_: The tweets the user engaged with (retweeted or favorited). These can be collected in two ways: 
  1) using the [user timeline](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline) (v1 API) or the [User Tweet timeline](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/introduction) (v2 API), and 
  2) using the [filter endpoint of the Streaming API](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/overview) (v1) with the _follow_ method (one process can track up to 5000 IDs), or the [Filtered Stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction) (v2) (one process can track 25 rules, each 512 characters long, assuming ~25 characters per user ID, that's about 500 users in total).
- _Pseudo-negatives_: The tweets created by the Twitter "friends" of the respondent (i.e. the users the respondent follows on Twitter). These include both the positives, as well as the tweets the user _may_ have seen, but did not engage with. Since we expect that even a small set of respondents will collectively follow a very large set of user profiles, we cannot use the follow method of the Streaming API. So, to collect these tweets we could use the 1% or 10% sample (for example via OSoMe, but for that we need to ask Fil and Sandro).
- Alternatively, we can get _both_ positives and pseudo-negatives calling the [GET statuses/home_timeline](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-home_timeline) endpoint. This returns up to 800 tweets and includes tweets/retweets by the authenticating user, and by the users they follow (the friends).  This is not affected by the 100,000 requests/24 h rate limit that was added by Twitter in 2019 to user_timeline (which applies per app, on top of the user auth and app auth limits). However, for this method to work it needs to be used within the authorizer app (i.e., at screening time). We cannot access this method afterwards since it requires access token from authenticating user.

We will need to decide how to proceed, based on the amount of respondents likely eligible, from the screening survey. We will discuss this next time (Feb 1st) with the rest of the team.

**Comment by glciampaglia** [comment]
We need to see if the new academic track gives us better options: https://developer.twitter.com/en/solutions/academic-research

**Comment by glciampaglia** [comment]
We discussed the issue with the rest of the team. This is what we decided to do:
- It's OK to use the filter endpoint of the streaming API (v1.1) for the positives.
- For the pseudo-negatives, it’s not clear whether the sampling API (either with the 1% public or the 10% provided via OSoME, which Fil and Sandro would let us access) would be better than instead polling all friends tweets via user_timeline (v1.1). It is worth doing an experiment with user_timeline to get the pseudo-negatives (the tweets of all the friends).
- We decided we should do a controlled experiment on our own accounts comparing sample vs user timeline.
- We also decided to update eligibility criteria for Twitter, see [survey design doc](https://docs.google.com/document/d/1IsetKhYmCcmTUIEK8Yx6eMEkKno3Rxx9SS37GTM29Cg/edit). We will need to run a test on recsys challenge data to see what is a good cutoff for the minimum # of engagements on NG sources.

**Comment by glciampaglia** [comment]
We tried to implement the controlled experiment of 2.), using Brendan's account as an example. Brendan follows a very large amount of people (~15K friends), so it would be worst case situation. What we found is:
- We were able to retrieve the list of friends immediately.
- However, when trying to fetch all their recent tweets via v1.1 user_timeline, we hit the monthly limit of the key (this was with the @ProfGLC account). 
- We collected ~500k tweets, which accounted for ~2,000 out of 15,000 of the friends.

We decided we will try again, but this time on Fil's account (`@OSoMe_IU`), which follows only 386 people.

**Comment by glciampaglia** [comment]
We also discussed the possibility of using the new v2 filtered stream endpoint. Since we now have academic access, we have many more rules available (20x, and each rule is twice as long). So, we track all the tweets that have a URL link to any of the domains from the newsguard list. That is, we could specify rules like this:
```
url:nytimes.com OR url:breitbart.com OR url:foxnews.com ...
```  
Quick math, if we assume ~20 character per domain name, that's about 37 domains per rule, and there are ~3000 domains in the newsguard, so that's about 100 rules, which is within the 1000 cap.

We could combine this information with the list of friend IDs, and that would allow us to build the pseudonegatives dataset.

We decided we will run a test, at first using 5% sampling (`sample:5`).

The only downside of this is that we do not include any engagement to non-newsguard content. So we may want to add an eligibility criterion that the user has engaged at least X number of times with sources in newsguard. This data can be collected with the authorizer (see #6).

**Comment by glciampaglia** [comment]
For the filtered stream, we ran some tests, collecting 1,000 tweets and measuring the time it takes to get them all. Using the 10% sampling, it took on average 3 minutes (at night it was slower, about 8 minutes). Extrapolating to 100% for 30 days, this is 360M tweets (1000 × (3600 / 3) × 10 × 30), and since our cap is 10M a month, we may need to sample at 1%. We decided we will run again the filter at 1% for one week, to see how many tweets we get.

Afterwards, we will collect using user tweet timeline, which should return tweets from the same period.

**Comment by glciampaglia** [comment]
We ran the stream for some time. We saw that almost all results were not matching any domain. It turns out that we were creating the rules incorrectly, and as a result we were matching "random" tweets (like tweets written in Portuguese). After some troubleshooting, we have decided to use the following rules:
```
sample:XX (url:"//cnn.com/" OR url:".cnn.com/" OR url:"//foxnews.com/" OR url:".foxnews.com/" OR [...])
```

This will match tweets whose URLs point to the "primary" domain (like cnn.com) or also subdomains (like sports.cnn.com). This should not give any invalid match. We are currently fixing some issues with the loading of the rules, and then we will collect a sample again at 100% rate, and see how many results we get. This will let us figure out the appropriate sampling rate.

**Comment by glciampaglia** [comment]
We checked the sample, there were no incorrect tweets. We also determined that a 10% sample rate should let us stay within the monthly caps. We are now deploying an instance of hoaxy on rincewind to start the collection.

**Comment by glciampaglia** [comment]
We have deployed a container with hoaxy. We are having an issue with the DB on rincewind. Once that is cleared we can start the data collection.

**Comment by glciampaglia** [comment]
We are running into another problem when running hoaxy: it does not find a package called cryptography (https://github.com/pyca/cryptography) that is needed by ScraPy. We need to add this on the docker image.

**Comment by RobertAndion** [comment]
Currently ran into an issue with the docker build and have posted an issue to their github. https://github.com/IUNetSci/hoaxy-backend/issues/70

**Comment by glciampaglia** [comment]
The docker image of Hoaxy now builds, we need to make sure that Hoaxy runs in it, and then deploy on rincewind.

**Comment by glciampaglia** [comment]
We have implemented the v2 streaming API into Hoaxy, and it works! We need to deploy on rincewind and let it run for some time to see if there are no more bugs.

**Comment by glciampaglia** [comment]
Hoaxy is now running on rincewind we can close this issue. If there are problems in the collection we may reopen it.
