### ISSUE TITLE
Display carousel correctly on small devices

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#96]
~~We need to adjust the CSS of the carousel so that it changes width when displayed on small screens.~~

We further discussed it, and it seems this is not very easy to do with CSS alone, so as a solution we will create a new set of slides in portrait mode, and load those instead when the screen is small and the device is in portrait mode (meaning screen width is smaller than screen height).

**Comment by thomasbiv** [comment]
WIP mobile slides that will replace normal slides for small devices in portrait mode:

https://docs.google.com/presentation/d/18bTqhFNuQT319DuFGfH68TNHv4f9utcSgGFQL60WFOQ/edit#slide=id.g1033b0f0f1a_0_73

**Comment by glciampaglia** [comment]
To make things simpler, instead of having two different sets of slides, we will try to see if we can display the mobile slides on both desktop and mobile.
