### ISSUE TITLE
Track feed scrolling

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#98]
We want to reimplement the tracking of scrolling in the feed. To do:
- [x] ~~Count a tweet as "seen" when at least 50% of the element area is in the screen.~~
- [x] Count a tweet as "seen" when the bottom/top of the tweet hits the bottom x% of the screen. (This is because small tweets at the end of the feed may never "reach" the middle of the screen.)   
- [x] When updating the count, save the current timestamp.
- [x] Keep a list in browser LocalStorage and append pair `(count, timestamp)` to it at every update

For the insertion in the database, see issue #104

**Comment by RobertAndion** [comment]
The top of the feed is now neglected at times, the new solution will be to account for all viewable tweets and have them share the same timestamp.

**Comment by RobertAndion** [comment]
I cannot create a scenario where tweets are missed with the current setup, can this be tested and if no one is able to replicate this issue I believe it can be closed.
