### ISSUE TITLE
Likes are of the quoted tweet, not the users quote of the tweet

### ISSUE THREAD

**Issue by RobertAndion** [CSDL-USF/Rockwell#99]
The likes should have shown as 0 and this is a backend issue to be fixed.

![image](https://user-images.githubusercontent.com/71728884/139292308-62c60320-fb2f-44c5-9364-4c42085b8d1f.png)
![image](https://user-images.githubusercontent.com/71728884/139292359-070b623a-c5e5-42f2-a6ef-33726137b287.png)

**Comment by saumyabhadani95** [comment]
Done.
